### ISSUE TITLE
训练过程中出现一些问题

### ISSUE THREAD

**Issue by fjw1049** [xueyongfu/chinese-layoutlm-v2#1]

**Comment by fjw1049** [comment]
Traceback (most recent call last):
  File "run_xfun_doc_embedding_train.py", line 243, in <module>
    main()
  File "run_xfun_doc_embedding_train.py", line 192, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/fjw/anaconda3/envs/xlm/lib/python3.7/site-packages/transformers/trainer.py", line 1172, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/home/fjw/anaconda3/envs/xlm/lib/python3.7/site-packages/transformers/trainer.py", line 1265, in _maybe_log_save_evaluate
    metrics = self.evaluate()
  File "/home/fjw/chinese-layoutlm-v2-master/examples/layoutlmft/trainers/xfun_trainer.py", line 192, in evaluate
    metric_key_prefix=metric_key_prefix,
  File "/home/fjw/chinese-layoutlm-v2-master/examples/layoutlmft/trainers/xfun_trainer.py", line 97, in prediction_loop
    outputs.pred_relations if pred_relations is None else pred_relations + outputs.pred_relations
AttributeError: 'dict' object has no attribute 'pred_relations'

**Comment by xueyongfu** [comment]
好的

**Comment by xueyongfu** [comment]
ok

**Comment by xueyongfu** [comment]
@fjw1049 有一些小bug，更新上去了，你在git pull一下吧
